### ISSUE TITLE
TODO tasks

### ISSUE THREAD

**Issue by skvedula** [skvedula/food-reviews#1]
data mining of amazon food reviews
steps:
- [ ] get data - download amazon food reviews data( from kaggle datasets)
- [ ] normalize data  - remove punctuations and convert to lower case(awk scripting)
- [ ] clean data - remove English stop words (scripting)
- [ ] data extraction - create unigram data and bi-gram data along with frequencies(CMU language toolkit)
- [ ] analyze the data which can be used for Indian conditions(as zomato search strings)

Note:
* all the above steps using python programming(single script ) - matching same end results.
